# Generated by Django 2.0 on 2018-02-22 19:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=32)),
                ('code', models.CharField(default='', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Classmapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classId', models.CharField(max_length=38)),
                ('Value', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='score_import',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='score_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='class',
            name='pre_req1',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='class',
            name='pre_req2',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='class',
            name='pre_req3',
            field=models.CharField(default='', max_length=9),
        ),
    ]
