# Generated by Django 2.0 on 2018-02-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20180222_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='co_req',
            field=models.CharField(default='', max_length=9),
        ),
    ]
