# Generated by Django 2.0 on 2018-02-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20180222_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='elig',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
